### ISSUE TITLE
ValueError: No password or public key available! when enabling tunnel

### ISSUE THREAD

**Issue by sabit** [subsite/tunnelman#7]
On KUbuntu 18.04, fails to establish tunnel with this error. Same tunnel/ssh login works fine from command line without password.
```
Opening tunnel mytunnel
Traceback (most recent call last):
  File "/data/devel/tunnelman/app/tunnel.py", line 42, in open_tunnel
    set_keepalive=self.app_conf.get('send_keepalive_seconds', 0)
  File "/home/username/.local/lib/python3.6/site-packages/sshtunnel.py", line 905, in __init__
    logger=self.logger
  File "/home/username/.local/lib/python3.6/site-packages/sshtunnel.py", line 1096, in _consolidate_auth
    raise ValueError('No password or public key available!')
ValueError: No password or public key available!
```

**Comment by subsite** [comment]
Thanks for the report, and thanks for trying out my app!

As far as I know, this should "just work" as long as you run tunnelman.py as the same user and in the same environment as you normally use key authentication. Just to clarify, did you get this error while running tunnelman from the same terminal window in which you just successfully ssh:d to the same host using password-less key authhentication? You have done all the `ssh-copy-id [host]` stuff?

I haven't tried it on KUbuntu, so it might be the sshtunnel library doesn't work in the same way as in normal (gnome) Ubuntu. 

Does KUbuntu have the key files in the same directory as Ubuntu, do you have a file named `id_rsa` in the directory `~/.ssh/`?
